In [1]:
import numpy as np
import pandas as pd

In [2]:
clase_1 = pd.read_csv("./data/clase_1.csv", sep = ";")
clase_1

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,No Apto
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
5,Leoncio Tena,Leoncio_Tena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
6,Odalys Torrijos,Odalys_Torrijos@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Eduardo Caparrós,Eduardo_Caparrós@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
8,Ignacio Goicoechea,Ignacio_Goicoechea@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
9,Clementina Santos,Clementina_Santos@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
10,Daniela Falcó,Daniela_Falcó@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
11,Abraham Vélez,Abraham_Vélez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,Apto
12,Maximiliano Menéndez,Maximiliano_Menéndez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
13,Anita Heredia,Anita_Heredia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
14,Eli Casas,Eli_Casas@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto

In [3]:
clase_2 = pd.read_csv("./data/clase_2.csv", sep = ";")
clase_2

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Guillermo Borrego,Guillermo_Borrego@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,No Apto,Apto,No Apto
1,Sergio Aguirre,Sergio_Aguirre@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,No Apto
2,Carlito Carrión,Carlito_Carrión@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,Apto
3,Haydée Figueroa,Haydée_Figueroa@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto
4,Chita Mancebo,Chita_Mancebo@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
5,Joaquina Asensio,Joaquina_Asensio@gmail.com,Febrero,12/02/2024,Madrid,No Apto,No Apto,Apto,Apto,Apto
6,Cristian Sarabia,Cristian_Sarabia@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,No Apto,Apto,Apto
7,Isabel Ibáñez,Isabel_Ibáñez@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
8,Desiderio Jordá,Desiderio_Jordá@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,No Apto,Apto
9,Rosalina Llanos,Rosalina_Llanos@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto

In [4]:
clase_3 = pd.read_csv("./data/clase_3.csv", sep = ";")
clase_3

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Amor Larrañaga,Amor_Larrañaga@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
1,Teodoro Alberola,Teodoro_Alberola@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,Apto,No Apto,Apto
2,Cleto Plana,Cleto_Plana@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
3,Aitana Sebastián,Aitana_Sebastián@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
4,Dolores Valbuena,Dolores_Valbuena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
5,Julie Ferrer,Julie_Ferrer@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,No Apto,Apto,No Apto
6,Mireia Cabañas,Mireia_Cabañas@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Flavia Amador,Flavia_Amador@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,Apto,Apto
8,Albino Macias,Albino_Macias@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
9,Ester Sánchez,Ester_Sánchez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,No Apto,Apto
10,Luis Miguel Galvez,Luis_Miguel_Galvez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
11,Loida Arellano,Loida_Arellano@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
12,Heraclio Duque,Heraclio_Duque@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,No Apto,No Apto
13,Herberto Figueras,Herberto_Figueras@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto

In [5]:
clase_4 = pd.read_csv("./data/clase_4.csv", sep = ";")
clase_4

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Teresa Laguna,Teresa_Laguna@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
1,Estrella Murillo,Estrella_Murillo@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
2,Ernesto Uriarte,Ernesto_Uriarte@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
3,Daniela Guitart,Daniela_Guitart@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto
4,Timoteo Trillo,Timoteo_Trillo@gmail.com,Febrero,12/02/2024,Valencia,No Apto,Apto,Apto,Apto,No Apto
5,Ricarda Tovar,Ricarda_Tovar@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
6,Alejandra Vilaplana,Alejandra_Vilaplana@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
7,Daniel Rosselló,Daniel_Rosselló@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
8,Rita Olivares,Rita_Olivares@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
9,Cleto Montes,Cleto_Montes@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
10,Marino Castilla,Marino_Castilla@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
11,Estefanía Valcárcel,Estefanía_Valcárcel@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,No Apto,Apto
12,Noemí Vilanova,Noemí_Vilanova@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto

In [6]:
claustro = pd.read_csv("./data/claustro.csv", sep = ";")
claustro

               Nombre Rol Vertical   Promocion    Campus   Modalidad
0           Noa Yáñez  TA       DS  Septiembre    Madrid  Presencial
1   Saturnina Benitez  TA       DS  Septiembre    Madrid  Presencial
2          Anna Feliu  TA       FS  Septiembre    Madrid  Presencial
3       Rosalva Ayuso  TA       FS  Septiembre  Valencia  Presencial
4    Ana Sofía Ferrer  TA       FS     Febrero  Valencia  Presencial
5     Angélica Corral  TA       FS     Febrero    Madrid  Presencial
6         Ariel Lledó  TA       DS  Septiembre    Madrid  Presencial
7         Mario Prats  LI       FS     Febrero  Valencia      Online
8   Luis Ángel Suárez  LI       FS  Septiembre    Madrid      Online
9  María Dolores Diaz  LI       DS  Septiembre    Madrid      Online

In [13]:
claustro_promocion = claustro[['Vertical','Promocion','Campus','Modalidad']]
claustro_promocion2= claustro_promocion.loc[2:]

In [25]:
clau3 = claustro_promocion2.sort_values("Promocion")
clau3["fecha"]=["12/02/2024","12/02/2024","12/02/2024","18/09/2023","18/09/2023","18/09/2023","18/09/2023","18/09/2023"]
clau3

  Vertical   Promocion    Campus   Modalidad       fecha
4       FS     Febrero  Valencia  Presencial  12/02/2024
5       FS     Febrero    Madrid  Presencial  12/02/2024
7       FS     Febrero  Valencia      Online  12/02/2024
2       FS  Septiembre    Madrid  Presencial  18/09/2023
3       FS  Septiembre  Valencia  Presencial  18/09/2023
6       DS  Septiembre    Madrid  Presencial  18/09/2023
8       FS  Septiembre    Madrid      Online  18/09/2023
9       DS  Septiembre    Madrid      Online  18/09/2023

In [26]:
clau3 = clau3.rename(columns={"Vertical":"vertical","Promocion":"mes_promo","Campus":"campus","Modalidad":"modalidad"})

In [28]:
clau3.to_csv("claustro.csv",index=False)

In [29]:
clau3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 4 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   vertical   8 non-null      object
 1   mes_promo  8 non-null      object
 2   campus     8 non-null      object
 3   modalidad  8 non-null      object
 4   fecha      8 non-null      object
dtypes: object(5)
memory usage: 384.0+ bytes

In [34]:
clau3["fecha"]=pd.to_datetime(clau3["fecha"], format='%d/%m/%Y')
clau3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 4 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   vertical   8 non-null      object
 1   mes_promo  8 non-null      object
 2   campus     8 non-null      object
 3   modalidad  8 non-null      object
 4   fecha      8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 384.0+ bytes

In [37]:
clau3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 4 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   vertical   8 non-null      object
 1   mes_promo  8 non-null      object
 2   campus     8 non-null      object
 3   modalidad  8 non-null      object
 4   fecha      8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 384.0+ bytes

In [38]:
clau3.to_csv("claustro.csv",index=False)

In [41]:
clau4 = claustro[['Nombre','Rol']]
clau4

               Nombre Rol
0           Noa Yáñez  TA
1   Saturnina Benitez  TA
2          Anna Feliu  TA
3       Rosalva Ayuso  TA
4    Ana Sofía Ferrer  TA
5     Angélica Corral  TA
6         Ariel Lledó  TA
7         Mario Prats  LI
8   Luis Ángel Suárez  LI
9  María Dolores Diaz  LI

In [43]:
clau4 = clau4.rename(columns={"Nombre":"nombre","Rol":"rol"})

In [44]:
clau4.to_csv("claustro2.csv",index=False)

In [46]:
clase12 = pd.concat([clase_1, clase_2], ignore_index=True)
clase12

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,No Apto
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
5,Leoncio Tena,Leoncio_Tena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
6,Odalys Torrijos,Odalys_Torrijos@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Eduardo Caparrós,Eduardo_Caparrós@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
8,Ignacio Goicoechea,Ignacio_Goicoechea@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
9,Clementina Santos,Clementina_Santos@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
10,Daniela Falcó,Daniela_Falcó@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
11,Abraham Vélez,Abraham_Vélez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,Apto
12,Maximiliano Menéndez,Maximiliano_Menéndez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
13,Anita Heredia,Anita_Heredia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
14,Eli Casas,Eli_Casas@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
15,Guillermo Borrego,Guillermo_Borrego@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,No Apto,Apto,No Apto
16,Sergio Aguirre,Sergio_Aguirre@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,No Apto
17,Carlito Carrión,Carlito_Carrión@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,Apto
18,Haydée Figueroa,Haydée_Figueroa@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto
19,Chita Mancebo,Chita_Mancebo@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
20,Joaquina Asensio,Joaquina_Asensio@gmail.com,Febrero,12/02/2024,Madrid,No Apto,No Apto,Apto,Apto,Apto
21,Cristian Sarabia,Cristian_Sarabia@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,No Apto,Apto,Apto
22,Isabel Ibáñez,Isabel_Ibáñez@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
23,Desiderio Jordá,Desiderio_Jordá@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,No Apto,Apto
24,Rosalina Llanos,Rosalina_Llanos@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto

In [47]:
clase12b = clase12[['Nombre','Email']]
clase12b

                  Nombre                           Email
0           Jafet Casals          Jafet_Casals@gmail.com
1       Jorge Manzanares      Jorge_Manzanares@gmail.com
2          Onofre Adadia         Onofre_Adadia@gmail.com
3           Merche Prada          Merche_Prada@gmail.com
4           Pilar Abella          Pilar_Abella@gmail.com
5           Leoncio Tena          Leoncio_Tena@gmail.com
6        Odalys Torrijos       Odalys_Torrijos@gmail.com
7       Eduardo Caparrós      Eduardo_Caparrós@gmail.com
8     Ignacio Goicoechea    Ignacio_Goicoechea@gmail.com
9      Clementina Santos     Clementina_Santos@gmail.com
10         Daniela Falcó         Daniela_Falcó@gmail.com
11         Abraham Vélez         Abraham_Vélez@gmail.com
12  Maximiliano Menéndez  Maximiliano_Menéndez@gmail.com
13         Anita Heredia         Anita_Heredia@gmail.com
14             Eli Casas             Eli_Casas@gmail.com
15     Guillermo Borrego     Guillermo_Borrego@gmail.com
16        Sergio Aguirre        Sergio_Aguirre@gmail.com
17       Carlito Carrión       Carlito_Carrión@gmail.com
18       Haydée Figueroa       Haydée_Figueroa@gmail.com
19         Chita Mancebo         Chita_Mancebo@gmail.com
20      Joaquina Asensio      Joaquina_Asensio@gmail.com
21      Cristian Sarabia      Cristian_Sarabia@gmail.com
22         Isabel Ibáñez         Isabel_Ibáñez@gmail.com
23       Desiderio Jordá       Desiderio_Jordá@gmail.com
24       Rosalina Llanos       Rosalina_Llanos@gmail.com

In [48]:
clase12b = clase12b.rename(columns={"Nombre":"nombre","Email":"email"})

In [49]:
clase34 = pd.concat([clase_3, clase_4], ignore_index=True)
clase34

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Amor Larrañaga,Amor_Larrañaga@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
1,Teodoro Alberola,Teodoro_Alberola@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,Apto,No Apto,Apto
2,Cleto Plana,Cleto_Plana@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
3,Aitana Sebastián,Aitana_Sebastián@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
4,Dolores Valbuena,Dolores_Valbuena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
5,Julie Ferrer,Julie_Ferrer@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,No Apto,Apto,No Apto
6,Mireia Cabañas,Mireia_Cabañas@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Flavia Amador,Flavia_Amador@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,Apto,Apto
8,Albino Macias,Albino_Macias@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
9,Ester Sánchez,Ester_Sánchez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,No Apto,Apto
10,Luis Miguel Galvez,Luis_Miguel_Galvez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
11,Loida Arellano,Loida_Arellano@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
12,Heraclio Duque,Heraclio_Duque@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,No Apto,No Apto
13,Herberto Figueras,Herberto_Figueras@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
14,Teresa Laguna,Teresa_Laguna@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
15,Estrella Murillo,Estrella_Murillo@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
16,Ernesto Uriarte,Ernesto_Uriarte@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
17,Daniela Guitart,Daniela_Guitart@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto
18,Timoteo Trillo,Timoteo_Trillo@gmail.com,Febrero,12/02/2024,Valencia,No Apto,Apto,Apto,Apto,No Apto
19,Ricarda Tovar,Ricarda_Tovar@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
20,Alejandra Vilaplana,Alejandra_Vilaplana@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
21,Daniel Rosselló,Daniel_Rosselló@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
22,Rita Olivares,Rita_Olivares@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
23,Cleto Montes,Cleto_Montes@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
24,Marino Castilla,Marino_Castilla@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
25,Estefanía Valcárcel,Estefanía_Valcárcel@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,No Apto,Apto
26,Noemí Vilanova,Noemí_Vilanova@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto

In [50]:
clase34b = clase34[['Nombre','Email']]
clase34b

                 Nombre                          Email
0        Amor Larrañaga       Amor_Larrañaga@gmail.com
1      Teodoro Alberola     Teodoro_Alberola@gmail.com
2           Cleto Plana          Cleto_Plana@gmail.com
3      Aitana Sebastián     Aitana_Sebastián@gmail.com
4      Dolores Valbuena     Dolores_Valbuena@gmail.com
5          Julie Ferrer         Julie_Ferrer@gmail.com
6        Mireia Cabañas       Mireia_Cabañas@gmail.com
7         Flavia Amador        Flavia_Amador@gmail.com
8         Albino Macias        Albino_Macias@gmail.com
9         Ester Sánchez        Ester_Sánchez@gmail.com
10   Luis Miguel Galvez   Luis_Miguel_Galvez@gmail.com
11       Loida Arellano       Loida_Arellano@gmail.com
12       Heraclio Duque       Heraclio_Duque@gmail.com
13    Herberto Figueras    Herberto_Figueras@gmail.com
14        Teresa Laguna        Teresa_Laguna@gmail.com
15     Estrella Murillo     Estrella_Murillo@gmail.com
16      Ernesto Uriarte      Ernesto_Uriarte@gmail.com
17      Daniela Guitart      Daniela_Guitart@gmail.com
18       Timoteo Trillo       Timoteo_Trillo@gmail.com
19        Ricarda Tovar        Ricarda_Tovar@gmail.com
20  Alejandra Vilaplana  Alejandra_Vilaplana@gmail.com
21      Daniel Rosselló      Daniel_Rosselló@gmail.com
22        Rita Olivares        Rita_Olivares@gmail.com
23         Cleto Montes         Cleto_Montes@gmail.com
24      Marino Castilla      Marino_Castilla@gmail.com
25  Estefanía Valcárcel  Estefanía_Valcárcel@gmail.com
26       Noemí Vilanova       Noemí_Vilanova@gmail.com

In [51]:
clase34b = clase34b.rename(columns={"Nombre":"nombre","Email":"email"})
clase34b

                 nombre                          email
0        Amor Larrañaga       Amor_Larrañaga@gmail.com
1      Teodoro Alberola     Teodoro_Alberola@gmail.com
2           Cleto Plana          Cleto_Plana@gmail.com
3      Aitana Sebastián     Aitana_Sebastián@gmail.com
4      Dolores Valbuena     Dolores_Valbuena@gmail.com
5          Julie Ferrer         Julie_Ferrer@gmail.com
6        Mireia Cabañas       Mireia_Cabañas@gmail.com
7         Flavia Amador        Flavia_Amador@gmail.com
8         Albino Macias        Albino_Macias@gmail.com
9         Ester Sánchez        Ester_Sánchez@gmail.com
10   Luis Miguel Galvez   Luis_Miguel_Galvez@gmail.com
11       Loida Arellano       Loida_Arellano@gmail.com
12       Heraclio Duque       Heraclio_Duque@gmail.com
13    Herberto Figueras    Herberto_Figueras@gmail.com
14        Teresa Laguna        Teresa_Laguna@gmail.com
15     Estrella Murillo     Estrella_Murillo@gmail.com
16      Ernesto Uriarte      Ernesto_Uriarte@gmail.com
17      Daniela Guitart      Daniela_Guitart@gmail.com
18       Timoteo Trillo       Timoteo_Trillo@gmail.com
19        Ricarda Tovar        Ricarda_Tovar@gmail.com
20  Alejandra Vilaplana  Alejandra_Vilaplana@gmail.com
21      Daniel Rosselló      Daniel_Rosselló@gmail.com
22        Rita Olivares        Rita_Olivares@gmail.com
23         Cleto Montes         Cleto_Montes@gmail.com
24      Marino Castilla      Marino_Castilla@gmail.com
25  Estefanía Valcárcel  Estefanía_Valcárcel@gmail.com
26       Noemí Vilanova       Noemí_Vilanova@gmail.com

In [52]:
nombremail = pd.concat([clase12b, clase34b], ignore_index=True)
nombremail

                  nombre                           email
0           Jafet Casals          Jafet_Casals@gmail.com
1       Jorge Manzanares      Jorge_Manzanares@gmail.com
2          Onofre Adadia         Onofre_Adadia@gmail.com
3           Merche Prada          Merche_Prada@gmail.com
4           Pilar Abella          Pilar_Abella@gmail.com
5           Leoncio Tena          Leoncio_Tena@gmail.com
6        Odalys Torrijos       Odalys_Torrijos@gmail.com
7       Eduardo Caparrós      Eduardo_Caparrós@gmail.com
8     Ignacio Goicoechea    Ignacio_Goicoechea@gmail.com
9      Clementina Santos     Clementina_Santos@gmail.com
10         Daniela Falcó         Daniela_Falcó@gmail.com
11         Abraham Vélez         Abraham_Vélez@gmail.com
12  Maximiliano Menéndez  Maximiliano_Menéndez@gmail.com
13         Anita Heredia         Anita_Heredia@gmail.com
14             Eli Casas             Eli_Casas@gmail.com
15     Guillermo Borrego     Guillermo_Borrego@gmail.com
16        Sergio Aguirre        Sergio_Aguirre@gmail.com
17       Carlito Carrión       Carlito_Carrión@gmail.com
18       Haydée Figueroa       Haydée_Figueroa@gmail.com
19         Chita Mancebo         Chita_Mancebo@gmail.com
20      Joaquina Asensio      Joaquina_Asensio@gmail.com
21      Cristian Sarabia      Cristian_Sarabia@gmail.com
22         Isabel Ibáñez         Isabel_Ibáñez@gmail.com
23       Desiderio Jordá       Desiderio_Jordá@gmail.com
24       Rosalina Llanos       Rosalina_Llanos@gmail.com
25        Amor Larrañaga        Amor_Larrañaga@gmail.com
26      Teodoro Alberola      Teodoro_Alberola@gmail.com
27           Cleto Plana           Cleto_Plana@gmail.com
28      Aitana Sebastián      Aitana_Sebastián@gmail.com
29      Dolores Valbuena      Dolores_Valbuena@gmail.com
30          Julie Ferrer          Julie_Ferrer@gmail.com
31        Mireia Cabañas        Mireia_Cabañas@gmail.com
32         Flavia Amador         Flavia_Amador@gmail.com
33         Albino Macias         Albino_Macias@gmail.com
34         Ester Sánchez         Ester_Sánchez@gmail.com
35    Luis Miguel Galvez    Luis_Miguel_Galvez@gmail.com
36        Loida Arellano        Loida_Arellano@gmail.com
37        Heraclio Duque        Heraclio_Duque@gmail.com
38     Herberto Figueras     Herberto_Figueras@gmail.com
39         Teresa Laguna         Teresa_Laguna@gmail.com
40      Estrella Murillo      Estrella_Murillo@gmail.com
41       Ernesto Uriarte       Ernesto_Uriarte@gmail.com
42       Daniela Guitart       Daniela_Guitart@gmail.com
43        Timoteo Trillo        Timoteo_Trillo@gmail.com
44         Ricarda Tovar         Ricarda_Tovar@gmail.com
45   Alejandra Vilaplana   Alejandra_Vilaplana@gmail.com
46       Daniel Rosselló       Daniel_Rosselló@gmail.com
47         Rita Olivares         Rita_Olivares@gmail.com
48          Cleto Montes          Cleto_Montes@gmail.com
49       Marino Castilla       Marino_Castilla@gmail.com
50   Estefanía Valcárcel   Estefanía_Valcárcel@gmail.com
51        Noemí Vilanova        Noemí_Vilanova@gmail.com

In [53]:
nombremail.to_csv("alumnos.csv",index=False)

In [63]:
listaproyectosa = clase12.columns.to_list()

In [64]:
listaproyectosab= listaproyectosa[5:]

In [66]:
listaproyectosb = clase34.columns.to_list()

In [68]:
listaproyectosba= listaproyectosb[5:]
listaproyectosba

['Proyecto_WebDev',
 'Proyecto_FrontEnd',
 'Proyecto_Backend',
 'Proyecto_React',
 'Proyecto_FullSatck']

In [69]:
listac= listaproyectosab+listaproyectosba

In [74]:
listad= pd.DataFrame({"nombre":listac})
listad

                nombre
0         Proyecto_HLF
1         Proyecto_EDA
2        Proyecto_BBDD
3          Proyecto_ML
4  Proyecto_Deployment
5      Proyecto_WebDev
6    Proyecto_FrontEnd
7     Proyecto_Backend
8       Proyecto_React
9   Proyecto_FullSatck

In [75]:
listad.to_csv("listaproyectos.csv",index=False)

In [ ]:
list_of_lists = df.values.tolist()

In [77]:
print(clase12.columns)

Index(['Nombre', 'Email', 'Promoción', 'Fecha_comienzo', 'Campus',
       'Proyecto_HLF', 'Proyecto_EDA', 'Proyecto_BBDD', 'Proyecto_ML',
       'Proyecto_Deployment'],
      dtype='object')

In [79]:
clase12c = clase12[["Proyecto_HLF","Proyecto_EDA","Proyecto_BBDD","Proyecto_ML","Proyecto_Deployment"]]
clase12c

   Proyecto_HLF Proyecto_EDA Proyecto_BBDD Proyecto_ML Proyecto_Deployment
0          Apto      No Apto          Apto        Apto                Apto
1          Apto      No Apto          Apto        Apto                Apto
2          Apto         Apto          Apto     No Apto                Apto
3          Apto      No Apto       No Apto        Apto             No Apto
4          Apto      No Apto          Apto        Apto                Apto
5          Apto         Apto          Apto        Apto                Apto
6       No Apto         Apto          Apto        Apto                Apto
7       No Apto         Apto          Apto        Apto                Apto
8          Apto         Apto          Apto     No Apto                Apto
9          Apto      No Apto          Apto        Apto                Apto
10         Apto         Apto          Apto        Apto                Apto
11         Apto      No Apto       No Apto        Apto                Apto
12         Apto      No Apto          Apto        Apto                Apto
13         Apto         Apto          Apto        Apto                Apto
14         Apto         Apto          Apto        Apto                Apto
15         Apto      No Apto       No Apto        Apto             No Apto
16         Apto      No Apto          Apto        Apto             No Apto
17         Apto      No Apto          Apto        Apto                Apto
18         Apto         Apto          Apto        Apto                Apto
19      No Apto         Apto       No Apto        Apto                Apto
20      No Apto      No Apto          Apto        Apto                Apto
21         Apto         Apto       No Apto        Apto                Apto
22      No Apto         Apto       No Apto        Apto                Apto
23      No Apto         Apto       No Apto     No Apto                Apto
24         Apto         Apto          Apto        Apto                Apto

In [81]:
list_of_notas12 = clase12c.values.tolist()
print(list_of_notas12)

[['Apto', 'No Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'No Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'No Apto', 'Apto'], ['Apto', 'No Apto', 'No Apto', 'Apto', 'No Apto'], ['Apto', 'No Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['No Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['No Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'No Apto', 'Apto'], ['Apto', 'No Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'No Apto', 'No Apto', 'Apto', 'Apto'], ['Apto', 'No Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'No Apto', 'No Apto', 'Apto', 'No Apto'], ['Apto', 'No Apto', 'Apto', 'Apto', 'No Apto'], ['Apto', 'No Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['No Apto', 'Apto', 'No Apto', 'Apto', 'Apto'], ['No Apto', 'No Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'No Apto', 'Apto', 'Apto'], ['No Apto', 'Apto', 'No Apto', 'Apto', 'Apto'], ['No Apto', 'Apto', 'No Apto', 'No Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto']]

In [82]:
clase34c=clase34[["Proyecto_WebDev","Proyecto_FrontEnd","Proyecto_Backend","Proyecto_React","Proyecto_FullSatck"]]
clase34c

,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Apto,Apto,Apto,Apto,No Apto
1,No Apto,No Apto,Apto,No Apto,Apto
2,Apto,No Apto,Apto,No Apto,Apto
3,Apto,No Apto,Apto,No Apto,Apto
4,Apto,Apto,Apto,Apto,No Apto
5,No Apto,No Apto,No Apto,Apto,No Apto
6,No Apto,Apto,Apto,Apto,Apto
7,Apto,Apto,No Apto,Apto,Apto
8,No Apto,Apto,Apto,Apto,Apto
9,No Apto,Apto,Apto,No Apto,Apto
10,No Apto,Apto,Apto,Apto,Apto
11,Apto,Apto,Apto,Apto,Apto
12,Apto,Apto,No Apto,No Apto,No Apto
13,Apto,Apto,Apto,Apto,Apto
14,Apto,Apto,Apto,Apto,Apto
15,Apto,Apto,No Apto,Apto,Apto
16,Apto,Apto,Apto,Apto,Apto
17,Apto,No Apto,No Apto,Apto,Apto
18,No Apto,Apto,Apto,Apto,No Apto
19,Apto,Apto,Apto,Apto,Apto
20,No Apto,No Apto,No Apto,Apto,Apto
21,No Apto,No Apto,Apto,No Apto,No Apto
22,No Apto,No Apto,No Apto,Apto,Apto
23,Apto,Apto,No Apto,Apto,Apto
24,No Apto,No Apto,Apto,No Apto,No Apto
25,Apto,Apto,No Apto,No Apto,Apto
26,Apto,No Apto,No Apto,Apto,Apto

In [83]:
list_of_notas34 = clase34c.values.tolist()
print(list_of_notas34)

[['Apto', 'Apto', 'Apto', 'Apto', 'No Apto'], ['No Apto', 'No Apto', 'Apto', 'No Apto', 'Apto'], ['Apto', 'No Apto', 'Apto', 'No Apto', 'Apto'], ['Apto', 'No Apto', 'Apto', 'No Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'No Apto'], ['No Apto', 'No Apto', 'No Apto', 'Apto', 'No Apto'], ['No Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'No Apto', 'Apto', 'Apto'], ['No Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['No Apto', 'Apto', 'Apto', 'No Apto', 'Apto'], ['No Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'No Apto', 'No Apto', 'No Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'No Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['Apto', 'No Apto', 'No Apto', 'Apto', 'Apto'], ['No Apto', 'Apto', 'Apto', 'Apto', 'No Apto'], ['Apto', 'Apto', 'Apto', 'Apto', 'Apto'], ['No Apto', 'No Apto', 'No Apto', 'Apto', 'Apto'], ['No Apto', 'No Apto', 'Apto', 'No Apto', 'No Apto'], ['No Apto', 'No Apto', 'No Apto', 'Apto', 'Apto'], ['Apto', 'Apto', 'No Apto', 'Apto', 'Apto'], ['No Apto', 'No Apto', 'Apto', 'No Apto', 'No Apto'], ['Apto', 'Apto', 'No Apto', 'No Apto', 'Apto'], ['Apto', 'No Apto', 'No Apto', 'Apto', 'Apto']]

In [84]:
list_of_notes=list_of_notas12+list_of_notas34

In [86]:
flat_list = [item for sublist in list_of_notes for item in sublist]

In [88]:
list_of_notes2 = pd.DataFrame({"notas":flat_list})
list_of_notes2.head(10)

     notas
0     Apto
1  No Apto
2     Apto
3     Apto
4     Apto
5     Apto
6  No Apto
7     Apto
8     Apto
9     Apto

In [89]:
list_of_notes2.to_csv("notas.csv",index=False)